# -*- coding: utf-8 -*-
"""Yolov8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jqpvdP6X_naw-f5pYJwSBLvOChpgOABb
"""



import os
HOME = os.getcwd()
print(HOME)

# Pip install method (recommended)
from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

from ultralytics import YOLO

from IPython.display import display, Image

"""**Custom Trainig**"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/MotorcycleHelmetandLicensePlateDetection

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/MotorcycleHelmetandLicensePlateDetection

!yolo task=detect mode=train model=yolov8s.pt data=data.yaml epochs=300 imgsz=640

!yolo predict model=yolov8n.pt source='/content/drive/MyDrive/Motorcycle Helmet and License plate detection.v6-datasetv6.yolov8/train/images/ADB03EC198566489_jpg.rf.1e0e4ebaaad3b95f6e2c017b06f01fc2.jpg'

!ls runs/detect/train2/

Image(filename='runs/detect/train/confusion_matrix.png', width=600)

Image(filename='runs/detect/train/results.png', width=600)

Image(filename='runs/detect/train2/val_batch0_pred.jpg', width=600)

!yolo task=detect mode=val model=runs/detect/train/weights/best.pt data=data.yaml

!yolo task=detect mode=predict model=runs/detect/train/weights/best.pt conf=0.25 source=test/images save=True

import glob
from IPython.display import Image, display

for image_path in glob.glob(f'runs/detect/predict/*.jpg')[:3]:
      display(Image(filename=image_path, width=600))
      print("\n")

